apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: ns
spec:
  selector:
    matchLabels:
      app: application
  template:
    spec:
      containers:
      - name: application
        resources:
          limits:
            cpu: "5"
            memory: 7000Mi
          requests:
            cpu: "5"
            memory: 7000Mi
