apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
  namespace: ns
spec:
  selector:
    matchLabels:
      app: application
  template:
    spec:
      containers:
      - name: application
        resources:
          limits:
            cpu: "1"
            memory: 1000Mi
          requests:
            cpu: "1"
            memory: 1000Mi
