apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  labels:
    app: application
  name: application
  namespace: ns
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: application
  pollingInterval: 15
  triggers:
    - type: cpu
      metricType: Utilization
      metadata:
        value: "80"
