apiVersion: v1
kind: Service
metadata:
  name: application
  labels:
    app: application
  namespace: ns
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: application
  selector:
    app: application
